name: CI
on:
  pull_request:
  push:
env:
  DATABASE_URL: sqlite:///./sql_l.db
jobs:
 lint:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - uses: Gr1N/setup-poetry@v8
     - uses: actions/setup-python@v4
       with:
         python-version: "3.11"
     - run: poetry install
     - run: poetry run mypy .
     - run: poetry run black .
